version: '3'
services:
  db:
    image: postgres:14.3
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES)DB: ${DB_NAME}
    container_name: volksdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
